"use client"

import { store } from "@/Store/store"
import { Provider } from "react-redux"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  )
}
